# ComfyUI_LiteLLM Configuration
# This file contains default settings. For API keys and sensitive data,
# use environment variables or create a .env file (see .env.example)

tmp_dir: comfy_path//data

# Base URLs for different providers
# API keys should be set as system environment variables, not in this config file
# For testing, use the .env file
OPENAI_BASE_URL: https://api.openai.com/v1/
KLUSTER_BASE_URL: https://api.kluster.ai/v1
# Internal configuration only - do not add API keys here
# This prevents interference with other ComfyUI custom node packages
