# ComfyUI_LiteLLM Configuration
# This file contains default settings. For API keys and sensitive data,
# use environment variables or create a .env file (see .env.example)

tmp_dir: comfy_path//data

# API Configuration - Use environment variables for actual keys
# Example: Set OPENAI_API_KEY, KLUSTER_API_KEY, etc. in your environment
BASE_API_KEY: ${BASE_API_KEY}
OPENAI_API_KEY: ${OPENAI_API_KEY}
ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
COHERE_API_KEY: ${COHERE_API_KEY}
KLUSTER_API_KEY: ${KLUSTER_API_KEY}

# Base URLs for different providers
OPENAI_BASE_URL: https://api.openai.com/v1/
KLUSTER_BASE_URL: https://api.kluster.ai/v1
